# Generated by Django 6.0.3 on 2026-04-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='exam_type',
            field=models.CharField(default='JEE MAIN', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='shift',
            field=models.IntegerField(default=1),
        ),
    ]
